import type { ContentItem, DashboardState } from "../domain/types";
import { contentToDraft, type ContentDraft, validateContentDraft } from "./content-draft";
export function hasApprovalSensitiveChanges(content: ContentItem, draft: ContentDraft) { return content.caption !== draft.caption || content.assetIds.join("|") !== draft.assetIds.join("|"); }
export function saveContentDraft(content: ContentItem | null, draft: ContentDraft, now: string): ContentItem {
  const validation = validateContentDraft(draft, now); if (!validation.valid) throw new Error(Object.values(validation.errors)[0]); const sensitive = content ? hasApprovalSensitiveChanges(content, draft) : false; const history = sensitive && content ? [...content.lineReview.history, { id: `approval-reset-${now}`, cycleId: content.lineReview.activeCycleId ?? "", event: "approval-reset" as const, comment: "แก้ไขสื่อหรือแคปชัน", occurredAt: now }] : content?.lineReview.history ?? [];
  return { id: content?.id ?? `content-${Date.now()}`, title: draft.title.trim(), categoryId: draft.categoryId, formatId: draft.formatId, owner: draft.owner, objective: draft.objective, priority: draft.priority, plannedWorkAt: draft.plannedWorkAt || null, lastWorkedAt: content?.lastWorkedAt ?? null, readyDate: draft.readyDate || null, productionStatus: draft.productionStatus, assetIds: [...draft.assetIds], processSteps: draft.processSteps.map((step) => ({ ...step })), caption: draft.caption, captionSource: content?.captionSource ?? null, schedules: draft.schedules.map((schedule) => ({ ...schedule })), referenceIds: [...draft.referenceIds], notes: draft.notes, localApproval: sensitive ? "pending" : draft.localApproval, lineReview: sensitive ? { ...content!.lineReview, status: "not-sent", activeCycleId: null, reviewCode: null, providerReceipts: [], lastEventAt: now, history } : content?.lineReview ?? { status: "not-sent", activeCycleId: null, reviewCode: null, providerReceipts: [], lastEventAt: null, history: [] }, createdAt: content?.createdAt ?? now, updatedAt: now, deletedAt: content?.deletedAt ?? null };
}
export function upsertDraft(state: DashboardState, content: ContentItem): DashboardState { const exists = state.contents.some((item) => item.id === content.id); return { ...state, contents: exists ? state.contents.map((item) => item.id === content.id ? content : item) : [...state.contents, content] }; }
export { contentToDraft };
